# Generated by Django 3.2.7 on 2021-10-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210929_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iphone6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
    ]
