# Generated by Django 3.2.7 on 2021-10-03 09:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_iphone6'),
    ]

    operations = [
        migrations.AddField(
            model_name='iphone6',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
